# EV Battery Health Prediction Datasest 

Kaggel: https://www.kaggle.com/datasets/srisyra02/ev-battery-health-prediction-dataset-20k

This dataset contains 20,000 simulated electric vehicle(EV) battery telemetry records designed for binary battery-failure prediction, where battery_failure indicates whether the battery is likely to fail (1 = failure, 0 = healthy). The dataset combines battery health, charging behavior, vehicle usage, environmental conditions, maintenance and diagnostic parameters to provide a realistic foundation for battery-health analysis and predictive modeling. It's built for classification modeling, EDA, feature engineering practice and battery-health research.

In [1]:
# import libaries 
import pandas as pd
import kagglehub
from pathlib import Path

In [2]:
# Download latest version
path = kagglehub.dataset_download("srisyra02/ev-battery-health-prediction-dataset-20k")

In [3]:
# find file name 
data_folder= Path(path)

for file in data_folder.iterdir():
    print(file.name)

ev battery_failure prediction Dataset.csv

In [4]:
# assign file to data frame 
df = pd.read_csv(data_folder / "ev battery_failure prediction Dataset.csv")
df.head()

,vehicle_id,vehicle_brand,vehicle_model,vehicle_type,manufacturing_year,battery_manufacturer,battery_chemistry,battery_capacity_kwh,drive_type,odometer_km,...,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles,battery_failure
0,EV100000,Ford,Mustang Mach-E,Truck,2022.0,Northvolt,NMC,NaN,AWD,290844.3,...,1.0,NaN,0.0,30.37,73.05,98.14,89.73,47.11,6748.0,0
1,EV100001,Tata,Tiago EV,Truck,2017.0,CATL,NCA,38.71,RWD,182239.5,...,0.0,1.0,0.0,67.94,82.50,NaN,NaN,55.38,5211.0,0
2,EV100002,Volkswagen,ID.3,Crossover,2016.0,BYD Battery,LFP,131.29,FWD,249369.3,...,0.0,1.0,0.0,74.84,90.33,60.02,86.84,74.54,4040.0,0
3,EV100003,NaN,Kona Electric,Sedan,2019.0,SK On,NMC,132.35,FWD,134830.2,...,NaN,0.0,0.0,46.94,56.69,66.43,93.93,31.69,NaN,0
4,EV100004,MG,ZS EV,SUV,2017.0,Guoxuan,LTO,25.72,AWD,158026.0,...,1.0,2.0,3.0,49.07,73.65,95.05,100.00,23.46,7290.0,0

Data set has sucessfully ingested

## Exploritory Data Analysis

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 70 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   vehicle_id                       20000 non-null  str
 1   vehicle_brand                    19356 non-null  str
 2   vehicle_model                    19180 non-null  str
 3   vehicle_type                     19356 non-null  str
 4   manufacturing_year               19018 non-null  float64
 5   battery_manufacturer             19382 non-null  str
 6   battery_chemistry                19278 non-null  str
 7   battery_capacity_kwh             19310 non-null  float64
 8   drive_type                       19274 non-null  str
 9   odometer_km                      19134 non-null  float64
 10  vehicle_age_years                19232 non-null  float64
 11  fleet_or_private                 19106 non-null  str
 12  battery_serial                   20000 non-null  str
 13  cycle_count                      19234 non-null  float64
 14  battery_health_percent           19102 non-null  float64
 15  state_of_charge                  19036 non-null  float64
 16  depth_of_discharge               19168 non-null  float64
 17  state_of_health                  19044 non-null  float64
 18  cell_voltage_avg                 19060 non-null  float64
 19  cell_voltage_std                 19144 non-null  float64
 20  pack_voltage                     19382 non-null  float64
 21  cell_temperature_avg             19232 non-null  float64
 22  cell_temperature_max             19056 non-null  float64
 23  internal_resistance              19202 non-null  float64
 24  charge_efficiency                19070 non-null  float64
 25  discharge_efficiency             19320 non-null  float64
 26  remaining_capacity               19386 non-null  float64
 27  capacity_loss_percent            19044 non-null  float64
 28  charging_cycles_last_month       19202 non-null  float64
 29  fast_charge_ratio                19012 non-null  float64
 30  slow_charge_ratio                19052 non-null  float64
 31  average_charge_power_kw          19096 non-null  float64
 32  average_charging_time            19386 non-null  float64
 33  overnight_charging_ratio         19260 non-null  float64
 34  home_charging_ratio              19020 non-null  float64
 35  charging_interruptions           19036 non-null  float64
 36  overcharge_events                19284 non-null  float64
 37  average_speed                    19016 non-null  float64
 38  average_trip_distance            19288 non-null  float64
 39  aggressive_acceleration_score    19272 non-null  float64
 40  hard_braking_score               19076 non-null  float64
 41  regenerative_braking_usage       19094 non-null  float64
 42  highway_driving_ratio            19352 non-null  float64
 43  city_driving_ratio               19276 non-null  float64
 44  daily_distance                   19144 non-null  float64
 45  average_ambient_temperature      19084 non-null  float64
 46  maximum_temperature              19178 non-null  float64
 47  minimum_temperature              19376 non-null  float64
 48  humidity                         19178 non-null  float64
 49  altitude                         19166 non-null  float64
 50  terrain_type                     19288 non-null  str
 51  dust_exposure                    19390 non-null  float64
 52  last_service_days                19266 non-null  float64
 53  cooling_system_health            19060 non-null  float64
 54  firmware_updates                 19378 non-null  float64
 55  previous_faults                  19372 non-null  float64
 56  maintenance_score                19156 non-null  float64
 57  thermal_runaway_risk             19280 non-null  float64
 58  voltage_imbalance                19276 non-null  float64
 59  temperature_variance             19364 non-null  float64
 60  sensor_fault_count               19032 non-null  float64
 61  BMS_warning_count                19094 non-null  float64
 62  abnormal_voltage_events          19240 non-null  float64
 63  battery_stress_index             19270 non-null  float64
 64  aging_score                      19164 non-null  float64
 65  thermal_health_score             19368 non-null  float64
 66  charging_quality_score           19282 non-null  float64
 67  driving_stress_score             19320 non-null  float64
 68  predicted_remaining_life_cycles  19102 non-null  float64
 69  battery_failure                  20000 non-null  int64
dtypes: float64(59), int64(1), str(10)
memory usage: 10.7 MB

This dataset has 70 features. It includes a mix of float, integer, and string data types. Most variables appear to have some missing values. The target variable battery_failure and the identifier variable vehicle_id have no missing values. No more than 5% misisng for each variable.

In [6]:
# missing summary 

missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percent": df.isnull().mean()*100
})

missing_summary = missing_summary[
    missing_summary["missing_count"]>0 
].sort_values("missing_percent", ascending=False)

missing_summary

                       missing_count  missing_percent
fast_charge_ratio                988             4.94
average_speed                    984             4.92
manufacturing_year               982             4.91
home_charging_ratio              980             4.90
sensor_fault_count               968             4.84
...                              ...              ...
battery_manufacturer             618             3.09
pack_voltage                     618             3.09
average_charging_time            614             3.07
remaining_capacity               614             3.07
dust_exposure                    610             3.05

[67 rows x 2 columns]

missingness is spread throughout the dataset between 3-5% per affected column

In [7]:
# view missingness by row 

df["missing_count"] = df.isnull().sum(axis=1)
df["missing_percent"] = df.isnull().mean(axis=1)*100

df[["missing_count", "missing_percent"]].describe()

       missing_count  missing_percent
count   20000.000000     20000.000000
mean        2.667200         3.756620
std         1.606603         2.262821
min         0.000000         0.000000
25%         1.000000         1.408451
50%         3.000000         4.225352
75%         4.000000         5.633803
max        11.000000        15.492958

There are 20,000 observations, and each row is missing an average of 2.67 values. The median row is missing 3 values, while the most incomplete row is missing 11 values (15.5%).

missing values are spread throguht the dataset 

Imputation is likely the most approatate apprach, depending on the distrubution and datatype. 

    - Approximately symmetric continuous variable → mean
    - Skewed continuous variable or variables with outliers → median
    - Categorical/string variable → mode or possibly "Unknown" if missingness itself has meaning
    - Integer variables → depends on what the integer represents. A count like sensor_fault_count may behave differently from a coded category like 1, 2, 3.

In [8]:
df.shape

(20000, 72)

In [9]:
# drop added misisng rows 
df.drop(columns=["missing_count", "missing_percent"], inplace=True)
df.shape

(20000, 70)

## Summary 

The data set was loaded and checked for null values. Missingness was seen throughout the dataset. The next step is to check the distribution of missingness and determine imputation strategies.